{
 "title": "Aggregator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "EON sensors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate(EON_counter_OK_total[1h])/(rate(EON_counter_FAULTY_total[1h])+rate(EON_counter_OK_total[1h])+rate(EON_counter_WARN_total[1h])))*100",
     "legendFormat": "OK %"
    },
    {
     "expr": "(rate(EON_counter_WARN_total[1h])/(rate(EON_counter_FAULTY_total[1h])+rate(EON_counter_OK_total[1h])+rate(EON_counter_WARN_total[1h])))*100",
     "legendFormat": "WARN %"
    }
   ]
  },
  {
   "title": "Electrica sensors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate(Electrica_counter_OK_total[1h])/(rate(Electrica_counter_FAULTY_total[1h])+rate(Electrica_counter_OK_total[1h])+rate(Electrica_counter_WARN_total[1h])))*100",
     "legendFormat": "OK %"
    },
    {
     "expr": "(rate(Electrica_counter_WARN_total[1h])/(rate(Electrica_counter_FAULTY_total[1h])+rate(Electrica_counter_OK_total[1h])+rate(Electrica_counter_WARN_total[1h])))*100",
     "legendFormat": "WARN %"
    }
   ]
  },
  {
   "title": "EON sensors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate(EON_counter_FAULTY_total[1h])/(rate(EON_counter_FAULTY_total[1h])+rate(EON_counter_OK_total[1h])+rate(EON_counter_WARN_total[1h])))*100",
     "legendFormat": "FAULTY"
    }
   ]
  },
  {
   "title": "Electrica sensors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate(Electrica_counter_FAULTY_total[1h])/(rate(Electrica_counter_FAULTY_total[1h])+rate(Electrica_counter_OK_total[1h])+rate(Electrica_counter_WARN_total[1h])))*100",
     "legendFormat": "FAULTY"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "EON_voltage", "legendFormat": "EON" },
    { "expr": "Electrica_voltage", "legendFormat": "Electrica" }
   ]
  },
  {
   "title": "Aggregator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aggregator_response_time_seconds_max",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "OK status",
   "type": "graph",
   "description": "Electrica and EON OK statuses",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "EON_counter_OK_total" },
    { "expr": "Electrica_counter_OK_total" }
   ]
  },
  {
   "title": "FAULTY status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Electrica_counter_FAULTY_total" },
    { "expr": "EON_counter_FAULTY_total" }
   ]
  }
 ]
}