apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors
  labels:
    app: sensors
    deployment: sensors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensors
  template:
    metadata:
      labels:
        app: sensors
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - image: docker.io/siposaron/sensor:0.0.2
          name: electrica-sensor
          imagePullPolicy: Always
          env:
          - name: CLIENT_NAME
            value: "Electrica"
          - name: AGGREGATOR_SERVICE_ENDPOINT
            value: "http://aggregator-service:8080/status"
          - name: JAVA_OPTS
            value: -Xmx256m -Xms256m
          - name: SERVER_PORT 
            value: "8080"
          - name: logging.logstash.enabled
            value: "true"
          - name: logging.logstash.url
            value: "ks16.codespring.ro:31500"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 291Mi
        - image: docker.io/siposaron/sensor:0.0.2
          name: eon-sensor
          imagePullPolicy: Always
          env:
          - name: CLIENT_NAME
            value: "EON"
          - name: AGGREGATOR_SERVICE_ENDPOINT
            value: "http://aggregator-service:8080/status"
          - name: JAVA_OPTS
            value: -Xmx256m -Xms256m  
          - name: SERVER_PORT 
            value: "8081"
          - name: logging.logstash.enabled
            value: "true"
          - name: logging.logstash.url
            value: "ks16.codespring.ro:31500"
          ports:
            - containerPort: 8081    
          resources:
            limits:
              memory: 291Mi